name: Enforce Approval for prod/pre

on:
  push:
    branches:
      - main

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for restricted file changes
        run: |
          if git diff --name-only origin/main HEAD | grep -E "myfolder/second.yml|myfolder/third.yml"; then
            echo "Error: Changes are not allowed!"
            exit 1
          fi